version: '2'
networks:
  graph:
    external: true
services:
  dse:
      image: datastax/dse-server:6.8.1
      command: [ -s -g ]
      container_name: dse
      environment:
        - "DS_LICENSE=accept"
        - "STUDIO_JVM_ARGS=-Xms2g -Xmx4g -Djava.io.tmpdir=/tmp"
      ports:
      - "9042:9042"
      cap_add:
      - IPC_LOCK
      ulimits:
        memlock: -1
      volumes:
      - "./data:/var/lib/cassandra"
      networks:
        - graph
  studio:
      image: datastax/dse-studio:6.8.1
      container_name: studio
      environment:
        - "DS_LICENSE=accept"
        - "STUDIO_JVM_ARGS=-Xms2g -Xmx4g -Djava.io.tmpdir=/tmp"
      depends_on:
        - dse
      ports:
        - "9091:9091"
      volumes:
      - "./notebooks:/var/lib/datastax-studio"
      networks:
        - graph
