apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: node
  name: node
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: node
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: node
    spec:
      containers:
      - env:
        - name: CASSANDRA_CGROUP_MEMORY_LIMIT
          value: "true"
        - name: CASSANDRA_SEEDS
          value: seed_node
        - name: DEBUG
          value: "true"
        - name: HEAP_NEWSIZE
          value: 300m
        - name: JVM_OPTS
          value: -Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler
        - name: MAX_HEAP_SIZE
          value: 1200m
        image: strapdata/elassandra:latest
        imagePullPolicy: ""
        name: node
        resources:
          limits:
            memory: "2097152e3"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
